### ISSUE TITLE
No need to wait after Wire.requestFrom() and no Wire.beginTransmission() or endTransmission() should be used with Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [jarzebski/Arduino-INA219#1]
When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library. There is nothing to wait for after the Wire.requestFrom(). The Wire.available() and Wire.read() only use that buffer, they are not involved in the I2C bus transaction.
The while-loop to wait for something can be removed.

The Wire.beginTransmission() and Wire.endTransmission() are only used when writing data. They should not be used with Wire.requestFrom().

**Comment by jarzebski** [comment]
fixed in master

**Comment by Koepel** [comment]
Please remove this line:
```
while(!Wire.available()) {};
```
